# Generated by Django 3.1.6 on 2021-11-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
