# Generated by Django 3.1.6 on 2021-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bookmark_mobileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='is_premium',
            field=models.BooleanField(default=0, verbose_name='Подписка'),
        ),
    ]
