# Generated by Django 3.1.6 on 2021-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money_limit',
            field=models.DecimalField(decimal_places=2, default=30000.0, max_digits=12, verbose_name='Денежный лимит'),
        ),
    ]
