# Generated by Django 3.1.6 on 2021-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_money_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='step_target',
            field=models.IntegerField(default=10000, verbose_name='Цель по шагам'),
        ),
    ]
