# Generated by Django 3.1.6 on 2021-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='money',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='income',
            name='money',
            field=models.FloatField(verbose_name='Сумма'),
        ),
    ]
