# Generated by Django 3.1.6 on 2021-11-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20211127_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=255, verbose_name='Иконка категории'),
        ),
    ]
