# Generated by Django 3.1.6 on 2021-11-29 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20211128_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 29), verbose_name='Дата'),
        ),
    ]
