# Generated by Django 3.1.6 on 2021-11-30 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20211129_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(default='Оплата товаров и услуг', max_length=210, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 30), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(default=datetime.date(2021, 11, 30), verbose_name='Дата'),
        ),
    ]
