# Generated by Django 3.1.6 on 2021-09-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_auto_20210911_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemedia',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Сноска'),
        ),
    ]
