# Generated by Django 3.1.6 on 2021-10-11 15:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_articlemedia_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemedia',
            name='rich_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
