# Generated by Django 3.1.6 on 2021-10-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0009_auto_20211015_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemedia',
            name='render',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
