# Generated by Django 3.1.6 on 2021-10-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0010_articlemedia_render'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemedia',
            name='render',
            field=models.TextField(blank=True, default=' ', verbose_name='HTML для приложения'),
        ),
    ]
