# Generated by Django 3.1.6 on 2021-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Наименование задания')),
            ],
            options={
                'verbose_name': 'TODO-лист',
                'verbose_name_plural': 'TODO-листы',
            },
        ),
    ]
