# Generated by Django 3.1.6 on 2021-11-27 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название упражнения')),
                ('description', models.TextField(blank=True, verbose_name='Описание упражнения')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='UserFitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('unit', models.CharField(default='м', max_length=20, verbose_name='Мера измерения')),
                ('progress', models.PositiveIntegerField(verbose_name='Прогресс упражнения')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущее упражнение')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitness', to='fitness.exercise', verbose_name='Упражнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фитнес-трекер пользователя',
                'verbose_name_plural': 'Фитнес-трекер пользователей',
            },
        ),
    ]
