# Generated by Django 3.1.6 on 2021-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20211127_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitness',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
