# Generated by Django 3.1.6 on 2021-11-27 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_auto_20211127_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitness',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
