# Generated by Django 3.1.6 on 2021-12-02 15:42

import config.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='qr_code',
            field=models.ImageField(default=None, upload_to=config.views.get_upload_to, verbose_name='QR'),
            preserve_default=False,
        ),
    ]
